t5:
  pretrained_model_name_or_path: 'QizhiPei/biot5-plus-base'
swin:
  img_size: [224, 224]
  num_classes: 0
  embed_dim: 192
  depths: [2,2,18,2]
  num_heads: [6,12,24,48]
  pretrained_model_path: 'weights/moedel/swin_transform_focalloss.pth'
multimodal:
  use_visual_feature: true
  trainable_visual: false
  visual_feature_dim: 1536